### PR TITLE
Fix imports searching (depth + types)

### LINKED ISSUE #56: Explicitly referenced types from other namespaces inside UNION types aren't imported
[`getRecordSchemas`](https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/main/scala/format/abstractions/Importer.scala#L82) fails to account for the possible presence of types from another namespace mentioned inside `UNION` types, meaning that those types will never be imported at the end of the day.

### PR DESCRIPTION
**Pull request by mcoffin**
Fix #56 

Search more types, and search deeper for imports.

### CODE REVIEW

**Comment by mcoffin** [comment]
Ping @julianpeeters. It would be great if you could take a look at this as we're having to host our own repositories for `avrohugger` and `sbt-avrohugger` in the meantime.

I know how it goes with finding time for PRs on pet projects, so no biggie, just thought I'd let you know.

**Comment by julianpeeters** [comment]
Looking good! Much improved, in fact. But, what, no tests!? 😄

Something like 

```js
{
  "type": "record",
  "name": "Event",
  "namespace": "protocol",
  "fields": [
    {
      "name": "sc",
      "type": {
        "name": "SR",
        "fields": [
          {
            "name": "constraints",
            "type": [
              "null",
              {
                "name": "C",
                "fields": [
                  {
                    "name": "blah",
                    "type": "string"
                  }
                ],
                "type": "record",
                "namespace": "model"
              }
            ]
          }
        ],
        "type": "record",
        "namespace": "model.v2"
      }
    }
  ]
}
```

needs to be minimized if possible, and added to the [existing import examples](https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/test/avro/import.avdl)(maybe rename it, convert it to avdl and stuff it in with [imported.avdl](https://github.com/julianpeeters/avrohugger/blob/master/avrohugger-core/src/test/avro/imported.avdl)?) in `test` and all the subprojects of `sbt-test` (note these `scripted` tests will require a locally published, bumped version of sbt-avrohugger in order to reflect to the changes)

**If you don't beat me to it, I expect to have time to add the tests and publish on Sat night or sometime on Sunday PST**

Thanks very much for this contribution, I already know a few who will appreciate it.

**Comment by julianpeeters** [comment]
Hmm, welp I didn't expect the existing test suite to have been broken. Those are passing again, but I only managed the [slightest start](https://github.com/julianpeeters/avrohugger/tree/imports), adding schemas in example directories trying to give a clue what needs to be tested (I'm ok foregoing Importer tests as long as there is good high-level coverage). I most likely won't have time to continue until later this week.

**Comment by mcoffin** [comment]
Thanks a bunch dude! I'll pull your stuff and I'll likely have time to fix this up either today or tomorrow!

**Comment by mcoffin** [comment]
@julianpeeters I added your `importedcomplex` schema file to all the tests, so this should be pullable soon.

If I have some extra time though, I'll write out some specs for the importers themselves, which would be a little more useful than just the end-to-end checking that we have already.

File: avrohugger-core/src/test/scala/util/AvrohuggerSpec.scala [hunk 1]
```diff
@@ -0,0 +1,101 @@
...
+
+  private def readFile(f: File): String = {
+    val source = Source.fromFile(f)
+    try source.mkString finally source.close()
+  }
+
+  val expectedBase = FileSystems.getDefault.getPath("avrohugger-core", "src", "test", "expected", sourceFormatName)
+  val generatedBase = FileSystems.getDefault.getPath("target", "generated-sources", sourceFormatName)
+
+  private def prefixedFileString(prefixPath: Path, p: Path) = {
```
Comment (mcoffin) [inline avrohugger-core/src/test/scala/util/AvrohuggerSpec.scala:49]: @julianpeeters can you sanity check this quickly though? Basically, it will look for `<expected>/path/to/Something.scala` if using `Standard`, or `Specific`, but look for `<expected>/path/to/model/Something.scala` if using `Scavro`. I've never used the scavro generator before, but this appeared to be how it worked. Since I didn't know how it works though, a quick sanity check if for sure necessary.

**Comment by mcoffin** [comment]
Note that if we decide to pull the test additions as-is, then it might be worthwhile to convert some of the other tests over to the new `GlobalTests` format, at least as a PoC to prove that I built enough generalization in to it to be applicable for a good amount of the tests.

**Review by julianpeeters — CHANGES_REQUESTED** [review]
Please use the existing testing framework.

The new test examples look good. Unit tests around the importer would be heroic, but I'm happy with this current coverage in `test`, just need coverage in `sbt-test` in order to publish (I'll get to that eventually, looks like you may have already started that 👍 ).

**Comment by mcoffin** [comment]
@julianpeeters I've never worked with `sbt-test` before, so I'm not entirely sure where to start. If I'm going to be the one to take a crack at that there'd be some ramp-up time.

**Comment by julianpeeters** [comment]
sry, priorities keep getting in my way.

No obligations, but jsyk: the tests in `test` catch regressions early, without having to publish local snapshots and plugin snapshots, but it's also possible that the tests in `test` accidentally ensure malformed SpecificRecords that don't de/serialize. The true integration tests are in the projects in `sbt-test`, which are regular sbt projects (that depend on the sbt-avrohugger plugin) but with an extra script file that gets run by `sbt scripted`.

If you were to run `sbt scripted` immediately after making changes to avrohugger, it would always pass because the projects in `sbt-test` would still be picking up the `"latest.integration"` of `sbt-avrohugger` off of maven central. To pick up the changes, do `publishLocal` on avrohugger, then bump and do `publishLocal` on `sbt-avrohugger` in order to get `sbt-test` to get the latest integration from your local ivy repo. PITA, but keeps the tests in the project whose code they depend on.

**Comment by julianpeeters** [comment]
Thanks again for your contribution, this is out now in avrohugger/sbt-avrohugger 0.14.0
